DROP TABLE IF EXISTS slugs;

CREATE TABLE IF NOT EXISTS slugs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL DEFAULT 'No description',
  created_at DATE NOT NULL DEFAULT CURRENT_DATE,
  user_id UUID NOT NULL
);

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users(
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  emaiL VARCHAR(255) NULL,
  photo VARCHAR(255) NULL
);

ALTER TABLE
  slugs
ADD
  CONSTRAINT fk_users_slugs FOREIGN KEY(user_id) REFERENCES users(id);